# Generated by Django 3.0.8 on 2020-07-22 16:35

from django.db import migrations, models
import django_richtexteditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post.', max_length=255, unique=True, verbose_name='title')),
                ('content', django_richtexteditor.fields.RichTextField(help_text='The content of the post.', verbose_name='content')),
                ('excerpt', django_richtexteditor.fields.RichTextField(help_text='The excerpt of the post.', verbose_name='excerpt')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-date_created', 'title'),
            },
        ),
    ]
